### ISSUE TITLE
Is running Alexandrite on the base domain suported?

### ISSUE THREAD

**Issue by ethernic** [sheodox/alexandrite#53]
I've been messing around with a self hosted Lemmy instance at ctrlaltelite.xyz. Right now I have Alexandrite site up on the base domain and currently have Lemmy-ui on m.ctrlaltelite.xyz. I also have a.ctrlaltelite.xyz pointing to Alexandrite.

The functionality on the base domain seems to be working but I'm missing some glyphs on the page in Firefox only (Brave/Edge work fine.) The glyphs are not missing on a.ctrlaltelite.xyz.

Missing glyphs:
![alexandrite](https://github.com/sheodox/alexandrite/assets/22920921/501149d6-d19d-4b3f-80ad-375f7f3908a4)

The relevant portion of my docker compose:
```yml
  alexandrite:
    image: ghcr.io/sheodox/alexandrite:latest
    hostname: alexandrite
    container_name: alexandrite
    restart: unless-stopped
    depends_on:
      - lemmy-app
    environment:
      - ALEXANDRITE_DEFAULT_INSTANCE=${ALEXANDRITE_DEFAULT_INSTANCE}
      - ALEXANDRITE_WELCOME_LEMMY_HELP=${ALEXANDRITE_WELCOME_LEMMY_HELP}
      - ALEXANDRITE_WELCOME_INSTANCE_HELP=${ALEXANDRITE_WELCOME_INSTANCE_HELP}
      - ALEXANDRITE_FORCE_INSTANCE=${ALEXANDRITE_FORCE_INSTANCE}
    networks:
      - backend
      - frontend
```

.env:
```ini
ALEXANDRITE_DEFAULT_INSTANCE=ctrlaltelite.xyz
ALEXANDRITE_WELCOME_LEMMY_HELP=false
ALEXANDRITE_WELCOME_INSTANCE_HELP=false
ALEXANDRITE_FORCE_INSTANCE=ctrlaltelite.xyz
```

My caddy config:
```
*.ctrlaltelite.xyz, ctrlaltelite.xyz {
	import init_external "ctrlaltelite.xyz"
	encode gzip zstd
	import caddy-common
	reverse_proxy alexandrite:3000

	@a host a.ctrlaltelite.xyz
	import logger "a.ctrlaltelite.xyz"
	handle @a {
		reverse_proxy alexandrite:3000
	}

	@lemmy {
		path /api/*
		path /pictrs/*
		path /feeds/*
		path /nodeinfo/*
		path /.well-known/*
	}

	@lemmy-hdr {
		header Accept application/*
	}

	@lemmy-post {
		method POST
	}

	handle @lemmy-hdr {
		reverse_proxy lemmy-app:8536
	}

	handle @lemmy {
		reverse_proxy lemmy-app:8536
	}

	handle @lemmy-post {
		reverse_proxy lemmy-app:8536
	}

	@m host m.ctrlaltelite.xyz
	import logger "m.ctrlaltelite.xyz"
	import caddy-common
	handle @m {
		reverse_proxy lemmy-ui:1234
	}

	@status host status.ctrlaltelite.xyz
	handle @status {
		reverse_proxy iamfoo:2001 {
	    header_up Host {http.reverse_proxy.upstream.hostport}
	  }
	  header {
	    -Server
	  }
	}
}
```
